import type { Product, Category, Testimonial } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'bags',
    name: 'Bags & Totes',
    nameArabic: 'الحقائب',
    description: 'Cotton and cord totes made to carry your everyday essentials.',
    descriptionArabic: 'حقائب كتف وتسوق مصنوعة من حبال القطن المتينة لحمل احتياجاتك اليومية.',
    count: 4,
    image: '/products/hadab-bag.jpg',
    accentBg: 'bg-blush-100/70',
    accentBorder: 'border-blush-300',
  },
  {
    id: 'clothing',
    name: 'Wearables',
    nameArabic: 'الملابس',
    description: 'Light cardigans, mesh tops, and waistcoats crocheted from soft natural fibers.',
    descriptionArabic: 'كارديجان خفيف وقطع محبوكة ناعمة من ألياف البامبو والكتان الطبيعي.',
    count: 0,
    image: '/products/hadab-cardigan.jpg',
    accentBg: 'bg-sage-100/70',
    accentBorder: 'border-sage-300',
  },
  {
    id: 'headwear',
    name: 'Hats & Headwear',
    nameArabic: 'أغطية الرأس',
    description: 'Bucket hats, fitted hats, and beanies crocheted from pure cotton.',
    descriptionArabic: 'قبعات بحافة متماسكة وطواقي مريحة محبوكة من خيوط القطن الصافي.',
    count: 0,
    image: '/products/hadab-hat.jpg',
    accentBg: 'bg-cream-100',
    accentBorder: 'border-brown-200',
  },
  {
    id: 'pouches',
    name: 'Accessories',
    nameArabic: 'الإكسسوارات',
    description: 'Clutches, small pouches, and crochet accessories with handmade trims.',
    descriptionArabic: 'كلاتشات ومحافظ صغيرة وحافظات يومية مزينة بشرّابات هَدَب اليدوية.',
    count: 0,
    image: '/products/hadab-pouch.jpg',
    accentBg: 'bg-burgundy-50/70',
    accentBorder: 'border-burgundy-200',
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'bag-hadab-classic',
    name: 'The Trapillo Shoulder Tote',
    nameArabic: 'حقيبة هَدَب المجدولة',
    price: 135,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'Signature Piece',
    tagArabic: 'قطعة مميزة',
    description: 'Made from charcoal and cream cotton cord, with loop handles and a strong base.',
    descriptionArabic: 'مصنوعة من حبال القطن الفاخرة بلوني الفحم والكريم، مع مقابض حلقية وقاعدة متينة.',
    stitchDetail: 'Single crochet ribbed wall with continuous braided handle',
    stitchDetailArabic: 'جدار مضلع بغرزة الحشو مع مقبض مجدول متصل',
    yarnType: '100% Recycled Cotton Cord (5mm)',
    yarnTypeArabic: 'خيط قطن معاد تدويره ١٠٠٪ (٥ ملم)',
    colorName: 'Charcoal & Cream Fleck',
    colorNameArabic: 'فحم وكريم منقط',
    colorHex: '#4A382F',
    isFeatured: true,
  },
  {
    id: 'bag-slouchy-market',
    name: 'The Slouchy Market Net',
    nameArabic: 'حقيبة السوق المنسوجة',
    price: 95,
    originalPrice: 120,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'Archive Drop',
    tagArabic: 'إصدار الأرشيف',
    description: 'An expansive open-lace market bag handcrafted from twisted linen cord with reinforced base gusset.',
    descriptionArabic: 'حقيبة تسوق شبكية واسعة محبوكة يدوياً من خيوط الكتان المجدولة مع قاعدة معززة.',
    stitchDetail: 'Open trellis knotting with double-thick base',
    stitchDetailArabic: 'عقد شبكية مفتوحة مع قاعدة مزدوجة السماكة',
    yarnType: 'Braided Linen & Raw Cotton',
    yarnTypeArabic: 'كتان مجدول وقطن خام',
    colorName: 'Unbleached Flax',
    colorNameArabic: 'كتان طبيعي خام',
    colorHex: '#D8CAB8',
    isFeatured: false,
    isSale: true,
  },
  {
    id: 'bag-cylinder-bucket',
    name: 'The Sculpted Cylinder Tote',
    nameArabic: 'حقيبة الأسطوانة الهيكلية',
    price: 145,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'New Arrival',
    tagArabic: 'وصل حديثاً',
    description: 'Architectural column shape worked in tight thermal crochet stitch for maximum structure and form retention.',
    descriptionArabic: 'تصميم أسطواني هندسي محبوك بغرزة الكروشيه الحرارية المتماسكة للحفاظ على ثبات الشكل.',
    stitchDetail: 'Thermal single crochet with integrated circular base',
    stitchDetailArabic: 'غرزة كروشيه حرارية مع قاعدة دائرية مدمجة',
    yarnType: 'Stiffened Cotton Ribbon Yarn',
    yarnTypeArabic: 'شريط قطني عالي التماسك',
    colorName: 'Espresso Roast',
    colorNameArabic: 'إسبريسو داكن',
    colorHex: '#2E221B',
    isFeatured: false,
  },
  {
    id: 'bag-fringe-basket',
    name: 'The Woven Fringe Basket',
    nameArabic: 'حقيبة السلة بشرّابات هَدَب',
    price: 110,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'Handmade Classic',
    tagArabic: 'كلاسيكي يدوي',
    description: 'Bespoke cotton cord basket bag finished with delicate handmade fringes and comfortable shoulder drop.',
    descriptionArabic: 'حقيبة سلة مميزة من حبال القطن الصافي مزينة بشرّابات هَدَب اليدوية الدقيقة مع حمالة كتف مريحة.',
    stitchDetail: 'Circular basket weave with hand-knotted fringe hem',
    stitchDetailArabic: 'حياكة سلة دائرية مع حافة بشرّابات معقودة يدوياً',
    yarnType: '100% Raw Cotton Cord',
    yarnTypeArabic: 'حبال قطن طبيعي ١٠٠٪',
    colorName: 'Desert Dune & Cream',
    colorNameArabic: 'كثبان صحراوية وكريم',
    colorHex: '#D8CAB8',
    isFeatured: true,
  },
];

export const SALE_PRODUCTS: Product[] = [];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    quote: 'You can tell right away that someone took real time making this bag. The stitching is even but still has that handmade feel you don\'t get from factory-made products.',
    quoteArabic: 'تلاحظ فوراً أن صانع الحقيبة منحها وقتاً حقيقياً وعناية بالغة. الغرز متناسقة جداً ومفعمة بالروح اليدوية الصادقة التي يستحيل أن تجدها في المنتجات التجارية الجاهزة.',
    author: 'Nour A.',
    authorArabic: 'نور أ.',
    location: 'Kuwait City, Kuwait',
    locationArabic: 'مدينة الكويت، الكويت',
    pieceName: 'The Trapillo Shoulder Tote',
    pieceNameArabic: 'توت الكتف ترابيلو',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'test-2',
    quote: 'The cotton cord texture is dense and holds its shape effortlessly. It feels intimate, quiet, and wonderfully distinct.',
    quoteArabic: 'قوام الحبل القطني متماسك ويحافظ على هيكله دون عناء. قطعة هادئة وأنيقة وتشعرك بالتميز في كل استخدام.',
    author: 'Reem K.',
    authorArabic: 'ريم خ.',
    location: 'Amman, Jordan',
    locationArabic: 'عمّان، الأردن',
    pieceName: 'The Waffle Horizon Tote',
    pieceNameArabic: 'توت الأفق بنقشة الوافل',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'test-3',
    quote: 'The fringe edging gives it such a warm personal touch. It has quickly become my go-to piece for morning coffee and gallery visits.',
    quoteArabic: 'تفاصيل الهَدَب على الأطراف تمنحها لمسة حميمية ودافئة. أصبحت رفيقتي اليومية في كل صباح ومناسباتي الهادئة.',
    author: 'Dana M.',
    authorArabic: 'دانة م.',
    location: 'Dubai, UAE',
    locationArabic: 'دبي، الإمارات',
    pieceName: 'The Dune Ribbon Carrier',
    pieceNameArabic: 'حقيبة شريط الكثبان',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...FEATURED_PRODUCTS,
  ...SALE_PRODUCTS.filter((sp) => !FEATURED_PRODUCTS.some((fp) => fp.id === sp.id)),
];
