import type { Product, Category, Testimonial } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'bags',
    name: 'Bags & Totes',
    nameArabic: 'الحقائب',
    description: 'Cotton and cord totes made to carry your everyday essentials.',
    descriptionArabic: 'حقائب كتف وتسوق مصنوعة من حبال القطن المتينة لحمل احتياجاتك اليومية.',
    count: 14,
    image: '/products/hadab-bag.jpg',
    accentBg: 'bg-blush-100/70',
    accentBorder: 'border-blush-300',
  },
  {
    id: 'clothing',
    name: 'Wearables',
    nameArabic: 'الملابس',
    description: 'Light cardigans, mesh tops, and waistcoats crocheted from soft natural fibers.',
    descriptionArabic: 'كارديجان خفيف وقطع محبوكة ناعمة من ألياف البامبو والكتان الطبيعي.',
    count: 8,
    image: '/products/hadab-cardigan.jpg',
    accentBg: 'bg-sage-100/70',
    accentBorder: 'border-sage-300',
  },
  {
    id: 'headwear',
    name: 'Hats & Headwear',
    nameArabic: 'أغطية الرأس',
    description: 'Bucket hats, fitted hats, and beanies crocheted from pure cotton.',
    descriptionArabic: 'قبعات بحافة متماسكة وطواقي مريحة محبوكة من خيوط القطن الصافي.',
    count: 11,
    image: '/products/hadab-hat.jpg',
    accentBg: 'bg-cream-100',
    accentBorder: 'border-brown-200',
  },
  {
    id: 'pouches',
    name: 'Accessories',
    nameArabic: 'الإكسسوارات',
    description: 'Clutches, small pouches, and crochet accessories with handmade trims.',
    descriptionArabic: 'كلاتشات ومحافظ صغيرة وحافظات يومية مزينة بشرّابات هَدَب اليدوية.',
    count: 12,
    image: '/products/hadab-pouch.jpg',
    accentBg: 'bg-burgundy-50/70',
    accentBorder: 'border-burgundy-200',
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'bag-hadab-classic',
    name: 'The Trapillo Shoulder Tote',
    nameArabic: 'حقيبة هَدَب المجدولة',
    price: 135,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'Signature Piece',
    tagArabic: 'قطعة مميزة',
    description: 'Made from charcoal and cream cotton cord, with loop handles and a strong base.',
    descriptionArabic: 'مصنوعة من حبال القطن الفاخرة بلوني الفحم والكريم، مع مقابض حلقية وقاعدة متينة.',
    stitchDetail: 'Single crochet ribbed wall with continuous braided handle',
    stitchDetailArabic: 'جدار مضلع بغرزة الحشو مع مقبض مجدول متصل',
    yarnType: '100% Recycled Cotton Cord (5mm)',
    yarnTypeArabic: 'خيط قطن معاد تدويره ١٠٠٪ (٥ ملم)',
    colorName: 'Charcoal & Cream Fleck',
    colorNameArabic: 'فحم وكريم منقط',
    colorHex: '#4A382F',
    isFeatured: true,
  },
  {
    id: 'bag-slouchy-market',
    name: 'The Slouchy Market Net',
    nameArabic: 'حقيبة السوق المنسوجة',
    price: 95,
    originalPrice: 120,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'Archive Drop',
    tagArabic: 'إصدار الأرشيف',
    description: 'An expansive open-lace market bag handcrafted from twisted linen cord with reinforced base gusset.',
    descriptionArabic: 'حقيبة تسوق شبكية واسعة محبوكة يدوياً من خيوط الكتان المجدولة مع قاعدة معززة.',
    stitchDetail: 'Open trellis knotting with double-thick base',
    stitchDetailArabic: 'عقد شبكية مفتوحة مع قاعدة مزدوجة السماكة',
    yarnType: 'Braided Linen & Raw Cotton',
    yarnTypeArabic: 'كتان مجدول وقطن خام',
    colorName: 'Unbleached Flax',
    colorNameArabic: 'كتان طبيعي خام',
    colorHex: '#D8CAB8',
    isFeatured: false,
    isSale: true,
  },
  {
    id: 'bag-cylinder-bucket',
    name: 'The Sculpted Cylinder Tote',
    nameArabic: 'حقيبة الأسطوانة الهيكلية',
    price: 145,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'New Atelier Release',
    tagArabic: 'إصدار ستوديو جديد',
    description: 'Architectural column shape worked in tight thermal crochet stitch for maximum structure and form retention.',
    descriptionArabic: 'تصميم أسطواني هندسي محبوك بغرزة الكروشيه الحرارية المتماسكة للحفاظ على ثبات الشكل.',
    stitchDetail: 'Thermal single crochet with integrated circular base',
    stitchDetailArabic: 'غرزة كروشيه حرارية مع قاعدة دائرية مدمجة',
    yarnType: 'Stiffened Cotton Ribbon Yarn',
    yarnTypeArabic: 'شريط قطني عالي التماسك',
    colorName: 'Espresso Roast',
    colorNameArabic: 'إسبريسو داكن',
    colorHex: '#2E221B',
    isFeatured: false,
  },
  {
    id: 'cardigan-open-mesh',
    name: 'The Open-Lace Bamboo Cardigan',
    nameArabic: 'كارديجان الغرز المفتوحة',
    price: 185,
    category: 'clothing',
    image: '/products/hadab-cardigan.jpg',
    textureImage: '/products/hadab-cardigan.jpg',
    tag: 'Atelier Edition',
    tagArabic: 'إصدار الأتيليه',
    description: 'A loose, flowing cardigan with decorative edges and wooden buttons. Takes over 22 hours to make by hand.',
    descriptionArabic: 'كارديجان فضفاض بأطراف زخرفية وأزرار خشبية طبيعية. يستغرق أكثر من ٢٢ ساعة حياكة يدوية.',
    stitchDetail: 'Treble mesh lace pattern with ribbed cuffs',
    stitchDetailArabic: 'غرزة دانتيل ثلاثية مع أساور مضلعة',
    yarnType: 'Bamboo & Linen Blend',
    yarnTypeArabic: 'مزيج البامبو والكتان الناعم',
    colorName: 'Sage Green & Oat',
    colorNameArabic: 'أخضر مريمي وشوفان',
    colorHex: '#7A8060',
    isFeatured: true,
  },
  {
    id: 'vest-ribbed-crop',
    name: 'The Ribbed Mockneck Vest',
    nameArabic: 'سديري الغرز العمودية',
    price: 118,
    originalPrice: 140,
    category: 'clothing',
    image: '/products/hadab-cardigan.jpg',
    textureImage: '/products/hadab-cardigan.jpg',
    tag: 'Archive Drop',
    tagArabic: 'إصدار الأرشيف',
    description: 'Structured sleeveless crop vest designed with deep armholes and hand-stitched horn buttons.',
    descriptionArabic: 'سديري قصير محكم بدون أكمام مع فتحات ذراع مريحة وأزرار عاجية مخيطة يدوياً.',
    stitchDetail: 'Back-loop half-double crochet ribbing',
    stitchDetailArabic: 'تضليع نصف عمود بالحلقة الخلفية',
    yarnType: 'Egyptian Combed Cotton',
    yarnTypeArabic: 'قطن مصري ممشط فاخر',
    colorName: 'Warm Sand',
    colorNameArabic: 'رمل دافئ',
    colorHex: '#E4DCCD',
    isFeatured: false,
    isSale: true,
  },
  {
    id: 'poncho-fringe-wrap',
    name: 'The Hadab Fringe Wrap Shawl',
    nameArabic: 'شال هَدَب المزركش',
    price: 165,
    category: 'clothing',
    image: '/products/hadab-cardigan.jpg',
    textureImage: '/products/hadab-cardigan.jpg',
    tag: 'Heritage Piece',
    tagArabic: 'قطعة تراثية',
    description: 'Airy triangle wrap draped with hand-knotted 4-inch hadab fringe along all perimeter borders.',
    descriptionArabic: 'شال مثلث خفيف مزين بشرّابات هَدَب معقودة يدوياً بطول ٤ بوصات على كامل الأطراف.',
    stitchDetail: 'Solomon knot lace with twisted hadab trim',
    stitchDetailArabic: 'عقدة سليمان مع أطراف هَدَب مبرومة',
    yarnType: 'Organic Cotton Fluff',
    yarnTypeArabic: 'خيوط قطن عضوي ناعمة',
    colorName: 'Dusk Heather',
    colorNameArabic: 'رمادي غسقي دافئ',
    colorHex: '#8C7A70',
    isFeatured: false,
  },
  {
    id: 'hat-waffle-bucket',
    name: 'The Waffle Stitch Bucket Hat',
    nameArabic: 'قبعة الغرز المضلعة',
    price: 68,
    category: 'headwear',
    image: '/products/hadab-hat.jpg',
    textureImage: '/products/hadab-hat.jpg',
    tag: 'Studio Essential',
    tagArabic: 'أساسي المشغل',
    description: 'A relaxed bucket hat with a textured brim that holds its shape, made from natural unbleached cotton.',
    descriptionArabic: 'قبعة مريحة بحافة مجسمة تحافظ على استقامتها، محبوكة من القطن الطبيعي غير المعالج.',
    stitchDetail: 'Textured waffle stitch with folded brim finish',
    stitchDetailArabic: 'غرزة الوافل المجسمة مع حافة مطوية',
    yarnType: 'Matte Organic Cotton Yarn',
    yarnTypeArabic: 'خيوط قطن عضوي غير لامعة',
    colorName: 'Warm Cream',
    colorNameArabic: 'كريم دافئ',
    colorHex: '#F2E8DD',
    isFeatured: true,
  },
  {
    id: 'hat-bell-cloche',
    name: 'The Desert Flora Cloche',
    nameArabic: 'قبعة الوردة الصحراوية',
    price: 62,
    originalPrice: 78,
    category: 'headwear',
    image: '/products/hadab-hat.jpg',
    textureImage: '/products/hadab-hat.jpg',
    tag: 'Archive Release',
    tagArabic: 'إصدار الأرشيف',
    description: '1920s-inspired bell silhouette with a gently downward-curved brim and subtle crown ridges.',
    descriptionArabic: 'تصميم جرسي مستوحى من كلاسيكيات العشرينات مع حافة منحنية بلطف وتفاصيل تاج دقيقة.',
    stitchDetail: 'Spiral continuous single crochet crown',
    stitchDetailArabic: 'تاج بحياكة حشو لولبية مستمرة',
    yarnType: 'Raw Seed Cotton Yarn',
    yarnTypeArabic: 'خيوط قطن طبيعي بذور خام',
    colorName: 'Oatmeal Tweed',
    colorNameArabic: 'شوفان تويد',
    colorHex: '#C5B9A8',
    isFeatured: false,
    isSale: true,
  },
  {
    id: 'hat-tasseled-beanie',
    name: 'The Slouched Tassel Beanie',
    nameArabic: 'طاقية الخيوط المنسدلة',
    price: 58,
    category: 'headwear',
    image: '/products/hadab-hat.jpg',
    textureImage: '/products/hadab-hat.jpg',
    tag: 'Everyday Classic',
    tagArabic: 'كلاسيكي يومي',
    description: 'Soft, breathable beanie finished with an understated hand-wrapped tassel charm on the rear brim.',
    descriptionArabic: 'طاقية ناعمة قابلة للتنفس مزينة بشرّابة هادئة ملفوفة يدوياً على الحافة الخلفية.',
    stitchDetail: 'Camel stitch knit-look ribbing',
    stitchDetailArabic: 'تضليع غرزة الجمل بمظهر محبوك',
    yarnType: 'Zero-Waste Recycled Cotton',
    yarnTypeArabic: 'قطن معاد تدويره بدون هدر',
    colorName: 'Deep Mahogany',
    colorNameArabic: 'ماهوجني داكن',
    colorHex: '#42281D',
    isFeatured: false,
  },
  {
    id: 'pouch-mini-hadab',
    name: 'The Fringe Dusk Clutch',
    nameArabic: 'كلاتش هَدَب العنابي',
    price: 88,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Limited Studio Piece',
    tagArabic: 'قطعة ستوديو محدودة',
    description: 'A foldover clutch in burgundy cord, finished with a handmade fringe tassel and loop closure.',
    descriptionArabic: 'كلاتش مطوي من حبال اللون العنابي الفاخر، مزين بشرّابة هَدَب يدوية وقفل حلقي متناسق.',
    stitchDetail: 'Moss stitch body with slip stitch edging & hand-tied tassel',
    stitchDetailArabic: 'غرزة الطحلب مع حواف منزلقة وشرّابة معقودة يدوياً',
    yarnType: 'Chunky Trapillo T-shirt Yarn',
    yarnTypeArabic: 'خيط ترابيلو قطني سميك',
    colorName: 'Burgundy Dusk',
    colorNameArabic: 'عنابي غسقي',
    colorHex: '#610C25',
    isFeatured: true,
  },
  {
    id: 'pouch-phone-sling',
    name: 'The Cord Crossbody Phone Sling',
    nameArabic: 'حقيبة الهاتف بالخيط المجدول',
    price: 62,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Daily Essential',
    tagArabic: 'أساسي يومي',
    description: 'Compact phone-sized pouch with a durable 48-inch tubular crochet strap and wooden loop toggle.',
    descriptionArabic: 'حافظة أنيقة بحجم الهاتف مع حزام كروشيه أسطواني بطول ٤٨ بوصة وقفل خشبي يدوي.',
    stitchDetail: 'Tight waist stitch with Romanian cord strap',
    stitchDetailArabic: 'غرزة خصر محكمة مع حزام الحبل الروماني',
    yarnType: 'Glazed Cotton Cord (3mm)',
    yarnTypeArabic: 'حبل قطني ناعم (٣ ملم)',
    colorName: 'Terracotta',
    colorNameArabic: 'طمي محروق (تيراكوتا)',
    colorHex: '#9E4734',
    isFeatured: false,
  },
  {
    id: 'pouch-key-charm',
    name: 'The Hadab Tassel AirTag Case',
    nameArabic: 'علاقة المفاتيح بشرّابة هَدَب',
    price: 34,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Atelier Gift',
    tagArabic: 'هدية المشغل',
    description: 'Delicate mini crochet pouch with antique brass key loop and handmade fringe accents.',
    descriptionArabic: 'حافظة كروشيه مصغرة مع حلقة مفاتيح نحاسية عتيقة وتفاصيل شرّابات هَدَب ناعمة.',
    stitchDetail: 'Micro single crochet with brass hardware join',
    stitchDetailArabic: 'غرزة حشو دقيقة مع تثبيت نحاسي مدمج',
    yarnType: 'Fine Mercerized Cotton',
    yarnTypeArabic: 'قطن ميرسيريزد رفيع فاخر',
    colorName: 'Antique Brass & Cream',
    colorNameArabic: 'نحاس عتيق وكريم',
    colorHex: '#BFA588',
    isFeatured: false,
  },
];

export const SALE_PRODUCTS: Product[] = [
  {
    id: 'pouch-mini-hadab-sale',
    name: 'The Fringe Dusk Clutch (Archive)',
    nameArabic: 'كلاتش هَدَب العنابي - أرشيف',
    price: 88,
    originalPrice: 110,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Archive Release',
    tagArabic: 'إصدار الأرشيف',
    description: 'A foldover clutch in burgundy cord with a handmade fringe tassel.',
    descriptionArabic: 'كلاتش مطوي من حبال العنابي مزين بشرّابة هَدَب يدوية الصنع.',
    stitchDetail: 'Moss stitch body with slip stitch edging',
    stitchDetailArabic: 'غرزة الطحلب مع حواف منزلقة أنيقة',
    yarnType: 'Chunky Trapillo Yarn',
    yarnTypeArabic: 'خيوط ترابيلو سميكة',
    colorName: 'Burgundy Dusk',
    colorNameArabic: 'عنابي غسقي',
    colorHex: '#610C25',
    isSale: true,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    quote: 'You can tell right away that someone took real time making this bag. The stitching is even but still has that handmade feel you don\'t get from factory-made products.',
    quoteArabic: 'تلاحظ فوراً أن صانع الحقيبة منحها وقتاً حقيقياً وعناية بالغة. الغرز متناسقة جداً ومفعمة بالروح اليدوية الصادقة التي يستحيل أن تجدها في المنتجات التجارية الجاهزة.',
    author: 'Nour A.',
    authorArabic: 'نور أ.',
    location: 'Kuwait City, Kuwait',
    locationArabic: 'مدينة الكويت، الكويت',
    pieceName: 'The Trapillo Shoulder Tote',
    pieceNameArabic: 'توت الكتف ترابيلو',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'test-2',
    quote: 'The cotton cord texture is dense and holds its shape effortlessly. It feels intimate, quiet, and wonderfully distinct.',
    quoteArabic: 'قوام الحبل القطني متماسك ويحافظ على هيكله دون عناء. قطعة هادئة وأنيقة وتشعرك بالتميز في كل استخدام.',
    author: 'Reem K.',
    authorArabic: 'ريم خ.',
    location: 'Amman, Jordan',
    locationArabic: 'عمّان، الأردن',
    pieceName: 'The Waffle Horizon Tote',
    pieceNameArabic: 'توت الأفق بنقشة الوافل',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'test-3',
    quote: 'The fringe edging gives it such a warm personal touch. It has quickly become my go-to piece for morning coffee and gallery visits.',
    quoteArabic: 'تفاصيل الهَدَب على الأطراف تمنحها لمسة حميمية ودافئة. أصبحت رفيقتي اليومية في كل صباح ومناسباتي الهادئة.',
    author: 'Dana M.',
    authorArabic: 'دانة م.',
    location: 'Dubai, UAE',
    locationArabic: 'دبي، الإمارات',
    pieceName: 'The Dune Ribbon Carrier',
    pieceNameArabic: 'حقيبة شريط الكثبان',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...FEATURED_PRODUCTS,
  ...SALE_PRODUCTS.filter((sp) => !FEATURED_PRODUCTS.some((fp) => fp.id === sp.id)),
];
