import type { Product, Category, Testimonial } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'bags',
    name: 'Bags & Totes',
    nameArabic: 'الحقائب',
    description: 'Cotton and cord totes made to carry your everyday essentials.',
    count: 14,
    image: '/products/hadab-bag.jpg',
    accentBg: 'bg-blush-100/70',
    accentBorder: 'border-blush-300',
  },
  {
    id: 'clothing',
    name: 'Wearables',
    nameArabic: 'الملابس',
    description: 'Light cardigans, mesh tops, and waistcoats crocheted from soft natural fibers.',
    count: 8,
    image: '/products/hadab-cardigan.jpg',
    accentBg: 'bg-sage-100/70',
    accentBorder: 'border-sage-300',
  },
  {
    id: 'headwear',
    name: 'Hats & Headwear',
    nameArabic: 'أغطية الرأس',
    description: 'Bucket hats, fitted hats, and beanies crocheted from pure cotton.',
    count: 11,
    image: '/products/hadab-hat.jpg',
    accentBg: 'bg-cream-100',
    accentBorder: 'border-brown-200',
  },
  {
    id: 'pouches',
    name: 'Accessories',
    nameArabic: 'الإكسسوارات',
    description: 'Clutches, small pouches, and crochet accessories with handmade trims.',
    count: 12,
    image: '/products/hadab-pouch.jpg',
    accentBg: 'bg-burgundy-50/70',
    accentBorder: 'border-burgundy-200',
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'bag-hadab-classic',
    name: 'The Trapillo Shoulder Tote',
    nameArabic: 'حقيبة هَدَب المجدولة',
    price: 135,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'Signature Piece',
    description: 'Made from charcoal and cream cotton cord, with loop handles and a strong base.',
    stitchDetail: 'Single crochet ribbed wall with continuous braided handle',
    yarnType: '100% Recycled Cotton Cord (5mm)',
    colorName: 'Charcoal & Cream Fleck',
    colorHex: '#4A382F',
    isFeatured: true,
  },
  {
    id: 'bag-slouchy-market',
    name: 'The Slouchy Market Net',
    nameArabic: 'حقيبة السوق المنسوجة',
    price: 95,
    originalPrice: 120,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'Archive Drop',
    description: 'An expansive open-lace market bag handcrafted from twisted linen cord with reinforced base gusset.',
    stitchDetail: 'Open trellis knotting with double-thick base',
    yarnType: 'Braided Linen & Raw Cotton',
    colorName: 'Unbleached Flax',
    colorHex: '#D8CAB8',
    isFeatured: false,
    isSale: true,
  },
  {
    id: 'bag-cylinder-bucket',
    name: 'The Sculpted Cylinder Tote',
    nameArabic: 'حقيبة الأسطوانة الهيكلية',
    price: 145,
    category: 'bags',
    image: '/products/hadab-bag.jpg',
    textureImage: '/products/hadab-bag.jpg',
    tag: 'New Atelier Release',
    description: 'Architectural column shape worked in tight thermal crochet stitch for maximum structure and form retention.',
    stitchDetail: 'Thermal single crochet with integrated circular base',
    yarnType: 'Stiffened Cotton Ribbon Yarn',
    colorName: 'Espresso Roast',
    colorHex: '#2E221B',
    isFeatured: false,
  },
  {
    id: 'cardigan-open-mesh',
    name: 'The Open-Lace Bamboo Cardigan',
    nameArabic: 'كارديجان الغرز المفتوحة',
    price: 185,
    category: 'clothing',
    image: '/products/hadab-cardigan.jpg',
    textureImage: '/products/hadab-cardigan.jpg',
    tag: 'Atelier Edition',
    description: 'A loose, flowing cardigan with decorative edges and wooden buttons. Takes over 22 hours to make by hand.',
    stitchDetail: 'Treble mesh lace pattern with ribbed cuffs',
    yarnType: 'Bamboo & Linen Blend',
    colorName: 'Sage Green & Oat',
    colorHex: '#7A8060',
    isFeatured: true,
  },
  {
    id: 'vest-ribbed-crop',
    name: 'The Ribbed Mockneck Vest',
    nameArabic: 'سديري الغرز العمودية',
    price: 118,
    originalPrice: 140,
    category: 'clothing',
    image: '/products/hadab-cardigan.jpg',
    textureImage: '/products/hadab-cardigan.jpg',
    tag: 'Archive Drop',
    description: 'Structured sleeveless crop vest designed with deep armholes and hand-stitched horn buttons.',
    stitchDetail: 'Back-loop half-double crochet ribbing',
    yarnType: 'Egyptian Combed Cotton',
    colorName: 'Warm Sand',
    colorHex: '#E4DCCD',
    isFeatured: false,
    isSale: true,
  },
  {
    id: 'poncho-fringe-wrap',
    name: 'The Hadab Fringe Wrap Shawl',
    nameArabic: 'شال هَدَب المزركش',
    price: 165,
    category: 'clothing',
    image: '/products/hadab-cardigan.jpg',
    textureImage: '/products/hadab-cardigan.jpg',
    tag: 'Heritage Piece',
    description: 'Airy triangle wrap draped with hand-knotted 4-inch hadab fringe along all perimeter borders.',
    stitchDetail: 'Solomon knot lace with twisted hadab trim',
    yarnType: 'Organic Cotton Fluff',
    colorName: 'Dusk Heather',
    colorHex: '#8C7A70',
    isFeatured: false,
  },
  {
    id: 'hat-waffle-bucket',
    name: 'The Waffle Stitch Bucket Hat',
    nameArabic: 'قبعة الغرز المضلعة',
    price: 68,
    category: 'headwear',
    image: '/products/hadab-hat.jpg',
    textureImage: '/products/hadab-hat.jpg',
    tag: 'Studio Essential',
    description: 'A relaxed bucket hat with a textured brim that holds its shape, made from natural unbleached cotton.',
    stitchDetail: 'Textured waffle stitch with folded brim finish',
    yarnType: 'Matte Organic Cotton Yarn',
    colorName: 'Warm Cream',
    colorHex: '#F2E8DD',
    isFeatured: true,
  },
  {
    id: 'hat-bell-cloche',
    name: 'The Desert Flora Cloche',
    nameArabic: 'قبعة الوردة الصحراوية',
    price: 62,
    originalPrice: 78,
    category: 'headwear',
    image: '/products/hadab-hat.jpg',
    textureImage: '/products/hadab-hat.jpg',
    tag: 'Archive Release',
    description: '1920s-inspired bell silhouette with a gently downward-curved brim and subtle crown ridges.',
    stitchDetail: 'Spiral continuous single crochet crown',
    yarnType: 'Raw Seed Cotton Yarn',
    colorName: 'Oatmeal Tweed',
    colorHex: '#C5B9A8',
    isFeatured: false,
    isSale: true,
  },
  {
    id: 'hat-tasseled-beanie',
    name: 'The Slouched Tassel Beanie',
    nameArabic: 'طاقية الخيوط المنسدلة',
    price: 58,
    category: 'headwear',
    image: '/products/hadab-hat.jpg',
    textureImage: '/products/hadab-hat.jpg',
    tag: 'Everyday Classic',
    description: 'Soft, breathable beanie finished with an understated hand-wrapped tassel charm on the rear brim.',
    stitchDetail: 'Camel stitch knit-look ribbing',
    yarnType: 'Zero-Waste Recycled Cotton',
    colorName: 'Deep Mahogany',
    colorHex: '#42281D',
    isFeatured: false,
  },
  {
    id: 'pouch-mini-hadab',
    name: 'The Fringe Dusk Clutch',
    nameArabic: 'كلاتش هَدَب العنابي',
    price: 88,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Limited Studio Piece',
    description: 'A foldover clutch in burgundy cord, finished with a handmade fringe tassel and loop closure.',
    stitchDetail: 'Moss stitch body with slip stitch edging & hand-tied tassel',
    yarnType: 'Chunky Trapillo T-shirt Yarn',
    colorName: 'Burgundy Dusk',
    colorHex: '#610C25',
    isFeatured: true,
  },
  {
    id: 'pouch-phone-sling',
    name: 'The Cord Crossbody Phone Sling',
    nameArabic: 'حقيبة الهاتف بالخيط المجدول',
    price: 62,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Daily Essential',
    description: 'Compact phone-sized pouch with a durable 48-inch tubular crochet strap and wooden loop toggle.',
    stitchDetail: 'Tight waist stitch with Romanian cord strap',
    yarnType: 'Glazed Cotton Cord (3mm)',
    colorName: 'Terracotta',
    colorHex: '#9E4734',
    isFeatured: false,
  },
  {
    id: 'pouch-key-charm',
    name: 'The Hadab Tassel AirTag Case',
    nameArabic: 'علاقة المفاتيح بشرّابة هَدَب',
    price: 34,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Atelier Gift',
    description: 'Delicate mini crochet pouch with antique brass key loop and handmade fringe accents.',
    stitchDetail: 'Micro single crochet with brass hardware join',
    yarnType: 'Fine Mercerized Cotton',
    colorName: 'Antique Brass & Cream',
    colorHex: '#BFA588',
    isFeatured: false,
  },
];

export const SALE_PRODUCTS: Product[] = [
  {
    id: 'pouch-mini-hadab-sale',
    name: 'The Fringe Dusk Clutch (Archive)',
    nameArabic: 'كلاتش هَدَب العنابي - أرشيف',
    price: 88,
    originalPrice: 110,
    category: 'pouches',
    image: '/products/hadab-pouch.jpg',
    textureImage: '/products/hadab-pouch.jpg',
    tag: 'Archive Release',
    description: 'A foldover clutch in burgundy cord with a handmade fringe tassel.',
    stitchDetail: 'Moss stitch body with slip stitch edging',
    yarnType: 'Chunky Trapillo Yarn',
    colorName: 'Burgundy Dusk',
    colorHex: '#610C25',
    isSale: true,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    quote: 'You can tell right away that someone took real time making this bag. The stitching is even but still has that handmade feel you don\'t get from factory-made products.',
    author: 'Nour A.',
    location: 'Kuwait City, Kuwait',
    pieceName: 'The Trapillo Shoulder Tote',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...FEATURED_PRODUCTS,
  ...SALE_PRODUCTS.filter((sp) => !FEATURED_PRODUCTS.some((fp) => fp.id === sp.id)),
];
